GET http://localhost:3000/users

###
GET http://localhost:3000/users?order=newest&offset=01&limit=2

###
GET http://localhost:3000/users/29022320-ff8b-4c48-a79d-029763bf2999

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "babo8117@naver.com",
  "firstName": "길동",
  "lastName": "홍",
  "address": "강원도 삼척시",
  "userPreference": { "receiveEmail": true }
}

###
PATCH http://localhost:3000/users/1d6bfa79-ec52-4aae-a437-e2283f5fddb3
Content-Type: application/json

{
  "firstName": "수영",
  "lastName": "정",
  "address": "경기도 하남시"
}

###
DELETE http://localhost:3000/users/1d6bfa79-ec52-4aae-a437-e2283f5fddb3

###
POST http://localhost:3000/users/29022320-ff8b-4c48-a79d-029763bf2999/save
Content-Type: application/json

{
  "productId": "43c62d5b-6e66-4d1c-9f47-14d1a1970fd1"
}





###
GET http://localhost:3000/products

###
GET http://localhost:3000/products?order=newest&category=ELECTRONICS&offset=1&limit=2

###
GET http://localhost:3000/products/1cc006a0-82a3-4e70-8d92-974d1ea9c3af

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "레노버 미니 PC",
  "description": "매운 작은 고추!",
  "price": 100000,
  "category": "ELECTRONICS",
  "stock": 0
}

###
PATCH http://localhost:3000/products/2adb18c2-d67b-4917-b684-59fc52d6e03b
Content-Type: application/json

{
  "name": "Brother P700",
  "description": "사무용, 작지만 다재다능한 레이블 메이커",
  "price": 80000,
  "stock": 10
}

###
DELETE http://localhost:3000/products/2adb18c2-d67b-4917-b684-59fc52d6e03b