GET http://localhost:3000/users?order=newest&offset=01&limit=3

###

GET http://localhost:3000/users/947dd6c6-8d93-4199-8329-e8363920a719

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "babo779@naver.com",
  "firstName": "길동",
  "lastName": "홍",
  "address": "강원도 삼척시",
  "userPreference": { "receiveEmail": true }
}

###

PATCH http://localhost:3000/users/aa48504d-fa48-45fc-aacc-6fd027ce2a53
Content-Type: application/json

{
  "firstName": "수영",
  "lastName:": "김",
  "address": "경기도 하남시"
}

###

DELETE http://localhost:3000/users/42e9a8d6-7df9-40e0-96fc-dd1d2c3be717

###

GET http://localhost:3000/products?order=newest&category=ELECTRONICS&offset=1&limit=2

###

GET http://localhost:3000/products/fbfdb439-16e6-4fde-ae4d-8371cd0e90d5
###

POST http://localhost:3000/products/fbfdb439-16e6-4fde-ae4d-8371cd0e90d5
Content-Type: application/json

{
  "name": "레노버 미니 PC",
  "description": "매운 작은 고추!",
  "price": 100000,
  "category": "ELECTRONICS",
  "stock": 20
}

###

PATCH http://localhost:3000/products/fbfdb439-16e6-4fde-ae4d-8371cd0e90d5
Content-Type: application/json

{
  "name": "Brother P700",
  "description": "사무용, 작지만 다재다능한 레이블 메이커",
  "price": 80000,
  "stock": 10
}

###

DELETE http://localhost:3000/products/fbfdb439-16e6-4fde-ae4d-8371cd0e90d5