GET http://localhost:3000/users

###

GET http://localhost:3000/users/8e0d77fd-a748-4bcd-89a8-8c4e0b59aea6

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "test5_kang@babo.com",
  "firstname": "김",
  "lastname": "경옥",
  "address": "경기도 하남시"
}

###

PATCH http://localhost:3000/users/82091134-cdc8-4efb-b9cf-0fc384b9d8f9
Content-Type: application/json

{
  "firstname": "경옥",
  "lastname": "김",
  "address": "경기도 하남시"
}

###

DELETE http://localhost:3000/users/82091134-cdc8-4efb-b9cf-0fc384b9d8f9

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/28cc77ca-3768-401e-991d-8c5f39645c1b
###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "레노버 미니 PC",
  "description": "매운 작은 고추!",
  "price": 100000,
  "category": "ELECTRONICS",
  "stock": 20
}

###

PATCH http://localhost:3000/products/2c7e5f3a-ed2d-467b-a2d7-2c1011275260
Content-Type: application/json

{
  "name": "Brother P700",
  "description": "사무용, 작지만 다재다능한 레이블 메이커"
}

###

DELETE http://localhost:3000/products/e97edcd7-9bcb-414a-bcc3-76bc6329c55b